name=SimpleFlashAudio
version=0.1.0
author=OrkaLxrd
maintainer=OrkaLxrd
sentence=Simple RAW audio player for Arduino and external SPI Flash.
paragraph=SimpleFlashAudio plays unsigned 8-bit mono RAW audio from W25Q SPI Flash using PWM output. Current tested target is ATmega328P Arduino Nano/Uno/Pro Mini.
category=Signal Input/Output
url=https://github.com/OrkaLxrd/SimpleFlashAudio
architectures=avr
includes=SimpleFlashAudio.h
